name: Signal K
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
collections:
  developers:
    output: true
plugins:
  - jekyll-mentions
  - jekyll-sitemap
url:
path:
logo: /images/signalk.gif
